[package]
name = "xxhash-sys"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[build-dependencies]
anyhow = "1.0.66"
bindgen = "0.62.0"
cc = "1.0.77"
